name: CI
env:
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  SECRET: ${{ secrets.SECRET }}
  TWITCH_ID: ${{ secrets.TWITCH_ID }}
  TWITCH_USER_NAME: ${{ secrets.TWITCH_USER_NAME }}
  USER_ID: ${{ secrets.USER_ID }}
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install modules
        run: yarn
      - name: Run tests
        run: yarn jest
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: npx semantic-release
