name: CI
env:
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  SECRET: ${{ secrets.SECRET }}
  TWITCH_ID: ${{ secrets.TWITCH_ID }}
  TWITCH_USER_NAME: ${{ secrets.TWITCH_USER_NAME }}
  USER_ID: ${{ secrets.USER_ID }}
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install modules and test
        run: |
          npm install
          jest test

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: npx semantic-release
